### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by falzm** [danielgtaylor/openapi-cli-generator#26]
Hi,

We're interested in using your software as a foundation to build our CLIs with, although it's currently missing some features we need: we'd gladly contribute those to your codebase, however it looks like this project has been inactive for a while now, so we're wondering if you're still maintaining it and so if it's still worth capitalizing on it rather than fork it and implement the changes we need on our end?

Thank you for your work! 👍

**Comment by danielgtaylor** [comment]
@falzm, I am still maintaining the project, but haven't had a ton of time to work on it (job, three kids, holidays, etc). I don't check my notifications for my open source projects every day as you can probably see :frowning_face:

I'm about to add support for the Authorization Code with PKCE OAuth2 login flow so that individual users can log in to the CLI rather than using a pre-shared secret. I would __love__ to have others contribute and make this project awesome.

FWIW we've used it in production at work since its inception with very few issues. It's been used to automate live streaming some very large sporting events.

There are a bunch of open issues that could use implementations!

**Comment by falzm** [comment]
Hi @danielgtaylor, thank you for clarifying and thank you for this project. Regarding contributions, do you prefer people to open an issue to discuss a change proposition before any PR or just open the PR and discuss there?

**Comment by danielgtaylor** [comment]
I'm okay with either. If it's a significant change it may be good to discuss so you don't waste time on an implementation, but it's up to you. Sometimes doing the implementation helps to get a deeper understanding of the problem. I'm open to including just about any new feature that doesn't break my use case.

Some things to think about as you work on features:

1. Would this change be breaking for existing CLI users?
  a. What is the recommended migration/upgrade strategy?
2. Is this generic enough that others would use it, or specific to my service/company? (e.g. pagination support)
3. Have I provided documentation so that others can easily use the feature?

**Comment by falzm** [comment]
Fair points, we'll consider those before submitting PRs. Thanks!
